# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import play_pb2 as play__pb2

GRPC_GENERATED_VERSION = '1.75.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in play_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class WebPlayStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.getPlayElement = channel.unary_unary(
                '/santiago.web.play.WebPlay/getPlayElement',
                request_serializer=play__pb2.GetPlayElementRequest.SerializeToString,
                response_deserializer=play__pb2.PlayElementResponse.FromString,
                _registered_method=True)
        self.getOwnedPlayElements = channel.unary_unary(
                '/santiago.web.play.WebPlay/getOwnedPlayElements',
                request_serializer=play__pb2.GetOwnedPlayElementsRequest.SerializeToString,
                response_deserializer=play__pb2.GetOwnedPlayElementsResponse.FromString,
                _registered_method=True)
        self.getOwnedPlayElementsV2 = channel.unary_unary(
                '/santiago.web.play.WebPlay/getOwnedPlayElementsV2',
                request_serializer=play__pb2.GetOwnedPlayElementsRequest.SerializeToString,
                response_deserializer=play__pb2.GetOwnedPlayElementsResponseV2.FromString,
                _registered_method=True)


class WebPlayServicer(object):
    """Missing associated documentation comment in .proto file."""

    def getPlayElement(self, request, context):
        """rpc createPlayElement (CreatePlayElementRequest) returns (PlayElementResponse) {}
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def getOwnedPlayElements(self, request, context):
        """rpc updatePlayElement (UpdatePlayElementRequest) returns (PlayElementResponse) {}
        rpc deletePlayElement (DeletePlayElementRequest) returns (DeletePlayElementResponse) {}
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def getOwnedPlayElementsV2(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_WebPlayServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'getPlayElement': grpc.unary_unary_rpc_method_handler(
                    servicer.getPlayElement,
                    request_deserializer=play__pb2.GetPlayElementRequest.FromString,
                    response_serializer=play__pb2.PlayElementResponse.SerializeToString,
            ),
            'getOwnedPlayElements': grpc.unary_unary_rpc_method_handler(
                    servicer.getOwnedPlayElements,
                    request_deserializer=play__pb2.GetOwnedPlayElementsRequest.FromString,
                    response_serializer=play__pb2.GetOwnedPlayElementsResponse.SerializeToString,
            ),
            'getOwnedPlayElementsV2': grpc.unary_unary_rpc_method_handler(
                    servicer.getOwnedPlayElementsV2,
                    request_deserializer=play__pb2.GetOwnedPlayElementsRequest.FromString,
                    response_serializer=play__pb2.GetOwnedPlayElementsResponseV2.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'santiago.web.play.WebPlay', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('santiago.web.play.WebPlay', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class WebPlay(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def getPlayElement(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/santiago.web.play.WebPlay/getPlayElement',
            play__pb2.GetPlayElementRequest.SerializeToString,
            play__pb2.PlayElementResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def getOwnedPlayElements(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/santiago.web.play.WebPlay/getOwnedPlayElements',
            play__pb2.GetOwnedPlayElementsRequest.SerializeToString,
            play__pb2.GetOwnedPlayElementsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def getOwnedPlayElementsV2(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/santiago.web.play.WebPlay/getOwnedPlayElementsV2',
            play__pb2.GetOwnedPlayElementsRequest.SerializeToString,
            play__pb2.GetOwnedPlayElementsResponseV2.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
