// source: authentication.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {missingRequire} reports error on implicit type usages.
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!
/* eslint-disable */
// @ts-nocheck

var jspb = require('google-protobuf');
var goog = jspb;
var global = (function() { return this || window || global || self || Function('return this')(); }).call(null);

goog.exportSymbol('proto.santiago.web.authentication.AuthCodeAuthentication', null, global);
goog.exportSymbol('proto.santiago.web.authentication.AuthenticationResponse', null, global);
goog.exportSymbol('proto.santiago.web.authentication.Duration', null, global);
goog.exportSymbol('proto.santiago.web.authentication.Empty', null, global);
goog.exportSymbol('proto.santiago.web.authentication.Platform', null, global);
goog.exportSymbol('proto.santiago.web.authentication.Player', null, global);
goog.exportSymbol('proto.santiago.web.authentication.ProtocolVersionOverride', null, global);
goog.exportSymbol('proto.santiago.web.authentication.Reason', null, global);
goog.exportSymbol('proto.santiago.web.authentication.TimeTravel', null, global);
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.santiago.web.authentication.Player = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.santiago.web.authentication.Player, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.santiago.web.authentication.Player.displayName = 'proto.santiago.web.authentication.Player';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.santiago.web.authentication.AuthCodeAuthentication = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.santiago.web.authentication.AuthCodeAuthentication, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.santiago.web.authentication.AuthCodeAuthentication.displayName = 'proto.santiago.web.authentication.AuthCodeAuthentication';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.santiago.web.authentication.Duration = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.santiago.web.authentication.Duration, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.santiago.web.authentication.Duration.displayName = 'proto.santiago.web.authentication.Duration';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.santiago.web.authentication.TimeTravel = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.santiago.web.authentication.TimeTravel, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.santiago.web.authentication.TimeTravel.displayName = 'proto.santiago.web.authentication.TimeTravel';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.santiago.web.authentication.ProtocolVersionOverride = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.santiago.web.authentication.ProtocolVersionOverride, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.santiago.web.authentication.ProtocolVersionOverride.displayName = 'proto.santiago.web.authentication.ProtocolVersionOverride';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.santiago.web.authentication.Empty = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.santiago.web.authentication.Empty, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.santiago.web.authentication.Empty.displayName = 'proto.santiago.web.authentication.Empty';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.santiago.web.authentication.AuthenticationResponse = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.santiago.web.authentication.AuthenticationResponse, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.santiago.web.authentication.AuthenticationResponse.displayName = 'proto.santiago.web.authentication.AuthenticationResponse';
}



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.santiago.web.authentication.Player.prototype.toObject = function(opt_includeInstance) {
  return proto.santiago.web.authentication.Player.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.santiago.web.authentication.Player} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.santiago.web.authentication.Player.toObject = function(includeInstance, msg) {
  var f, obj = {
    nucleusid: jspb.Message.getFieldWithDefault(msg, 1, 0),
    personaid: jspb.Message.getFieldWithDefault(msg, 2, 0),
    platform: jspb.Message.getFieldWithDefault(msg, 3, 0)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.santiago.web.authentication.Player}
 */
proto.santiago.web.authentication.Player.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.santiago.web.authentication.Player;
  return proto.santiago.web.authentication.Player.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.santiago.web.authentication.Player} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.santiago.web.authentication.Player}
 */
proto.santiago.web.authentication.Player.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {number} */ (reader.readInt64());
      msg.setNucleusid(value);
      break;
    case 2:
      var value = /** @type {number} */ (reader.readInt64());
      msg.setPersonaid(value);
      break;
    case 3:
      var value = /** @type {!proto.santiago.web.authentication.Platform} */ (reader.readEnum());
      msg.setPlatform(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.santiago.web.authentication.Player.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.santiago.web.authentication.Player.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.santiago.web.authentication.Player} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.santiago.web.authentication.Player.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getNucleusid();
  if (f !== 0) {
    writer.writeInt64(
      1,
      f
    );
  }
  f = message.getPersonaid();
  if (f !== 0) {
    writer.writeInt64(
      2,
      f
    );
  }
  f = message.getPlatform();
  if (f !== 0.0) {
    writer.writeEnum(
      3,
      f
    );
  }
};


/**
 * optional int64 nucleusId = 1;
 * @return {number}
 */
proto.santiago.web.authentication.Player.prototype.getNucleusid = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 1, 0));
};


/**
 * @param {number} value
 * @return {!proto.santiago.web.authentication.Player} returns this
 */
proto.santiago.web.authentication.Player.prototype.setNucleusid = function(value) {
  return jspb.Message.setProto3IntField(this, 1, value);
};


/**
 * optional int64 personaId = 2;
 * @return {number}
 */
proto.santiago.web.authentication.Player.prototype.getPersonaid = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 2, 0));
};


/**
 * @param {number} value
 * @return {!proto.santiago.web.authentication.Player} returns this
 */
proto.santiago.web.authentication.Player.prototype.setPersonaid = function(value) {
  return jspb.Message.setProto3IntField(this, 2, value);
};


/**
 * optional Platform platform = 3;
 * @return {!proto.santiago.web.authentication.Platform}
 */
proto.santiago.web.authentication.Player.prototype.getPlatform = function() {
  return /** @type {!proto.santiago.web.authentication.Platform} */ (jspb.Message.getFieldWithDefault(this, 3, 0));
};


/**
 * @param {!proto.santiago.web.authentication.Platform} value
 * @return {!proto.santiago.web.authentication.Player} returns this
 */
proto.santiago.web.authentication.Player.prototype.setPlatform = function(value) {
  return jspb.Message.setProto3EnumField(this, 3, value);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.santiago.web.authentication.AuthCodeAuthentication.prototype.toObject = function(opt_includeInstance) {
  return proto.santiago.web.authentication.AuthCodeAuthentication.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.santiago.web.authentication.AuthCodeAuthentication} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.santiago.web.authentication.AuthCodeAuthentication.toObject = function(includeInstance, msg) {
  var f, obj = {
    authcode: jspb.Message.getFieldWithDefault(msg, 1, ""),
    platform: jspb.Message.getFieldWithDefault(msg, 2, 0),
    redirecturi: jspb.Message.getFieldWithDefault(msg, 3, ""),
    patchversion: jspb.Message.getFieldWithDefault(msg, 4, ""),
    protocolversion: jspb.Message.getFieldWithDefault(msg, 5, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.santiago.web.authentication.AuthCodeAuthentication}
 */
proto.santiago.web.authentication.AuthCodeAuthentication.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.santiago.web.authentication.AuthCodeAuthentication;
  return proto.santiago.web.authentication.AuthCodeAuthentication.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.santiago.web.authentication.AuthCodeAuthentication} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.santiago.web.authentication.AuthCodeAuthentication}
 */
proto.santiago.web.authentication.AuthCodeAuthentication.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setAuthcode(value);
      break;
    case 2:
      var value = /** @type {!proto.santiago.web.authentication.Platform} */ (reader.readEnum());
      msg.setPlatform(value);
      break;
    case 3:
      var value = /** @type {string} */ (reader.readString());
      msg.setRedirecturi(value);
      break;
    case 4:
      var value = /** @type {string} */ (reader.readString());
      msg.setPatchversion(value);
      break;
    case 5:
      var value = /** @type {string} */ (reader.readString());
      msg.setProtocolversion(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.santiago.web.authentication.AuthCodeAuthentication.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.santiago.web.authentication.AuthCodeAuthentication.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.santiago.web.authentication.AuthCodeAuthentication} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.santiago.web.authentication.AuthCodeAuthentication.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getAuthcode();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getPlatform();
  if (f !== 0.0) {
    writer.writeEnum(
      2,
      f
    );
  }
  f = /** @type {string} */ (jspb.Message.getField(message, 3));
  if (f != null) {
    writer.writeString(
      3,
      f
    );
  }
  f = /** @type {string} */ (jspb.Message.getField(message, 4));
  if (f != null) {
    writer.writeString(
      4,
      f
    );
  }
  f = /** @type {string} */ (jspb.Message.getField(message, 5));
  if (f != null) {
    writer.writeString(
      5,
      f
    );
  }
};


/**
 * optional string authCode = 1;
 * @return {string}
 */
proto.santiago.web.authentication.AuthCodeAuthentication.prototype.getAuthcode = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.santiago.web.authentication.AuthCodeAuthentication} returns this
 */
proto.santiago.web.authentication.AuthCodeAuthentication.prototype.setAuthcode = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional Platform platform = 2;
 * @return {!proto.santiago.web.authentication.Platform}
 */
proto.santiago.web.authentication.AuthCodeAuthentication.prototype.getPlatform = function() {
  return /** @type {!proto.santiago.web.authentication.Platform} */ (jspb.Message.getFieldWithDefault(this, 2, 0));
};


/**
 * @param {!proto.santiago.web.authentication.Platform} value
 * @return {!proto.santiago.web.authentication.AuthCodeAuthentication} returns this
 */
proto.santiago.web.authentication.AuthCodeAuthentication.prototype.setPlatform = function(value) {
  return jspb.Message.setProto3EnumField(this, 2, value);
};


/**
 * optional string redirectUri = 3;
 * @return {string}
 */
proto.santiago.web.authentication.AuthCodeAuthentication.prototype.getRedirecturi = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 3, ""));
};


/**
 * @param {string} value
 * @return {!proto.santiago.web.authentication.AuthCodeAuthentication} returns this
 */
proto.santiago.web.authentication.AuthCodeAuthentication.prototype.setRedirecturi = function(value) {
  return jspb.Message.setField(this, 3, value);
};


/**
 * Clears the field making it undefined.
 * @return {!proto.santiago.web.authentication.AuthCodeAuthentication} returns this
 */
proto.santiago.web.authentication.AuthCodeAuthentication.prototype.clearRedirecturi = function() {
  return jspb.Message.setField(this, 3, undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.santiago.web.authentication.AuthCodeAuthentication.prototype.hasRedirecturi = function() {
  return jspb.Message.getField(this, 3) != null;
};


/**
 * optional string patchVersion = 4;
 * @return {string}
 */
proto.santiago.web.authentication.AuthCodeAuthentication.prototype.getPatchversion = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 4, ""));
};


/**
 * @param {string} value
 * @return {!proto.santiago.web.authentication.AuthCodeAuthentication} returns this
 */
proto.santiago.web.authentication.AuthCodeAuthentication.prototype.setPatchversion = function(value) {
  return jspb.Message.setField(this, 4, value);
};


/**
 * Clears the field making it undefined.
 * @return {!proto.santiago.web.authentication.AuthCodeAuthentication} returns this
 */
proto.santiago.web.authentication.AuthCodeAuthentication.prototype.clearPatchversion = function() {
  return jspb.Message.setField(this, 4, undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.santiago.web.authentication.AuthCodeAuthentication.prototype.hasPatchversion = function() {
  return jspb.Message.getField(this, 4) != null;
};


/**
 * optional string protocolVersion = 5;
 * @return {string}
 */
proto.santiago.web.authentication.AuthCodeAuthentication.prototype.getProtocolversion = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 5, ""));
};


/**
 * @param {string} value
 * @return {!proto.santiago.web.authentication.AuthCodeAuthentication} returns this
 */
proto.santiago.web.authentication.AuthCodeAuthentication.prototype.setProtocolversion = function(value) {
  return jspb.Message.setField(this, 5, value);
};


/**
 * Clears the field making it undefined.
 * @return {!proto.santiago.web.authentication.AuthCodeAuthentication} returns this
 */
proto.santiago.web.authentication.AuthCodeAuthentication.prototype.clearProtocolversion = function() {
  return jspb.Message.setField(this, 5, undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.santiago.web.authentication.AuthCodeAuthentication.prototype.hasProtocolversion = function() {
  return jspb.Message.getField(this, 5) != null;
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.santiago.web.authentication.Duration.prototype.toObject = function(opt_includeInstance) {
  return proto.santiago.web.authentication.Duration.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.santiago.web.authentication.Duration} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.santiago.web.authentication.Duration.toObject = function(includeInstance, msg) {
  var f, obj = {
    seconds: jspb.Message.getFieldWithDefault(msg, 1, 0),
    nanos: jspb.Message.getFieldWithDefault(msg, 2, 0)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.santiago.web.authentication.Duration}
 */
proto.santiago.web.authentication.Duration.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.santiago.web.authentication.Duration;
  return proto.santiago.web.authentication.Duration.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.santiago.web.authentication.Duration} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.santiago.web.authentication.Duration}
 */
proto.santiago.web.authentication.Duration.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {number} */ (reader.readInt64());
      msg.setSeconds(value);
      break;
    case 2:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setNanos(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.santiago.web.authentication.Duration.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.santiago.web.authentication.Duration.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.santiago.web.authentication.Duration} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.santiago.web.authentication.Duration.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getSeconds();
  if (f !== 0) {
    writer.writeInt64(
      1,
      f
    );
  }
  f = message.getNanos();
  if (f !== 0) {
    writer.writeInt32(
      2,
      f
    );
  }
};


/**
 * optional int64 seconds = 1;
 * @return {number}
 */
proto.santiago.web.authentication.Duration.prototype.getSeconds = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 1, 0));
};


/**
 * @param {number} value
 * @return {!proto.santiago.web.authentication.Duration} returns this
 */
proto.santiago.web.authentication.Duration.prototype.setSeconds = function(value) {
  return jspb.Message.setProto3IntField(this, 1, value);
};


/**
 * optional int32 nanos = 2;
 * @return {number}
 */
proto.santiago.web.authentication.Duration.prototype.getNanos = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 2, 0));
};


/**
 * @param {number} value
 * @return {!proto.santiago.web.authentication.Duration} returns this
 */
proto.santiago.web.authentication.Duration.prototype.setNanos = function(value) {
  return jspb.Message.setProto3IntField(this, 2, value);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.santiago.web.authentication.TimeTravel.prototype.toObject = function(opt_includeInstance) {
  return proto.santiago.web.authentication.TimeTravel.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.santiago.web.authentication.TimeTravel} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.santiago.web.authentication.TimeTravel.toObject = function(includeInstance, msg) {
  var f, obj = {
    offset: (f = msg.getOffset()) && proto.santiago.web.authentication.Duration.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.santiago.web.authentication.TimeTravel}
 */
proto.santiago.web.authentication.TimeTravel.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.santiago.web.authentication.TimeTravel;
  return proto.santiago.web.authentication.TimeTravel.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.santiago.web.authentication.TimeTravel} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.santiago.web.authentication.TimeTravel}
 */
proto.santiago.web.authentication.TimeTravel.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new proto.santiago.web.authentication.Duration;
      reader.readMessage(value,proto.santiago.web.authentication.Duration.deserializeBinaryFromReader);
      msg.setOffset(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.santiago.web.authentication.TimeTravel.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.santiago.web.authentication.TimeTravel.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.santiago.web.authentication.TimeTravel} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.santiago.web.authentication.TimeTravel.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getOffset();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      proto.santiago.web.authentication.Duration.serializeBinaryToWriter
    );
  }
};


/**
 * optional Duration offset = 1;
 * @return {?proto.santiago.web.authentication.Duration}
 */
proto.santiago.web.authentication.TimeTravel.prototype.getOffset = function() {
  return /** @type{?proto.santiago.web.authentication.Duration} */ (
    jspb.Message.getWrapperField(this, proto.santiago.web.authentication.Duration, 1));
};


/**
 * @param {?proto.santiago.web.authentication.Duration|undefined} value
 * @return {!proto.santiago.web.authentication.TimeTravel} returns this
*/
proto.santiago.web.authentication.TimeTravel.prototype.setOffset = function(value) {
  return jspb.Message.setWrapperField(this, 1, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.santiago.web.authentication.TimeTravel} returns this
 */
proto.santiago.web.authentication.TimeTravel.prototype.clearOffset = function() {
  return this.setOffset(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.santiago.web.authentication.TimeTravel.prototype.hasOffset = function() {
  return jspb.Message.getField(this, 1) != null;
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.santiago.web.authentication.ProtocolVersionOverride.prototype.toObject = function(opt_includeInstance) {
  return proto.santiago.web.authentication.ProtocolVersionOverride.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.santiago.web.authentication.ProtocolVersionOverride} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.santiago.web.authentication.ProtocolVersionOverride.toObject = function(includeInstance, msg) {
  var f, obj = {
    original: jspb.Message.getFieldWithDefault(msg, 1, ""),
    overridden: jspb.Message.getFieldWithDefault(msg, 2, ""),
    reason: jspb.Message.getFieldWithDefault(msg, 3, 0)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.santiago.web.authentication.ProtocolVersionOverride}
 */
proto.santiago.web.authentication.ProtocolVersionOverride.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.santiago.web.authentication.ProtocolVersionOverride;
  return proto.santiago.web.authentication.ProtocolVersionOverride.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.santiago.web.authentication.ProtocolVersionOverride} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.santiago.web.authentication.ProtocolVersionOverride}
 */
proto.santiago.web.authentication.ProtocolVersionOverride.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setOriginal(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setOverridden(value);
      break;
    case 3:
      var value = /** @type {!proto.santiago.web.authentication.Reason} */ (reader.readEnum());
      msg.setReason(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.santiago.web.authentication.ProtocolVersionOverride.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.santiago.web.authentication.ProtocolVersionOverride.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.santiago.web.authentication.ProtocolVersionOverride} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.santiago.web.authentication.ProtocolVersionOverride.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getOriginal();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getOverridden();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
  f = message.getReason();
  if (f !== 0.0) {
    writer.writeEnum(
      3,
      f
    );
  }
};


/**
 * optional string original = 1;
 * @return {string}
 */
proto.santiago.web.authentication.ProtocolVersionOverride.prototype.getOriginal = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.santiago.web.authentication.ProtocolVersionOverride} returns this
 */
proto.santiago.web.authentication.ProtocolVersionOverride.prototype.setOriginal = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional string overridden = 2;
 * @return {string}
 */
proto.santiago.web.authentication.ProtocolVersionOverride.prototype.getOverridden = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * @param {string} value
 * @return {!proto.santiago.web.authentication.ProtocolVersionOverride} returns this
 */
proto.santiago.web.authentication.ProtocolVersionOverride.prototype.setOverridden = function(value) {
  return jspb.Message.setProto3StringField(this, 2, value);
};


/**
 * optional Reason reason = 3;
 * @return {!proto.santiago.web.authentication.Reason}
 */
proto.santiago.web.authentication.ProtocolVersionOverride.prototype.getReason = function() {
  return /** @type {!proto.santiago.web.authentication.Reason} */ (jspb.Message.getFieldWithDefault(this, 3, 0));
};


/**
 * @param {!proto.santiago.web.authentication.Reason} value
 * @return {!proto.santiago.web.authentication.ProtocolVersionOverride} returns this
 */
proto.santiago.web.authentication.ProtocolVersionOverride.prototype.setReason = function(value) {
  return jspb.Message.setProto3EnumField(this, 3, value);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.santiago.web.authentication.Empty.prototype.toObject = function(opt_includeInstance) {
  return proto.santiago.web.authentication.Empty.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.santiago.web.authentication.Empty} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.santiago.web.authentication.Empty.toObject = function(includeInstance, msg) {
  var f, obj = {

  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.santiago.web.authentication.Empty}
 */
proto.santiago.web.authentication.Empty.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.santiago.web.authentication.Empty;
  return proto.santiago.web.authentication.Empty.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.santiago.web.authentication.Empty} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.santiago.web.authentication.Empty}
 */
proto.santiago.web.authentication.Empty.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.santiago.web.authentication.Empty.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.santiago.web.authentication.Empty.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.santiago.web.authentication.Empty} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.santiago.web.authentication.Empty.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.santiago.web.authentication.AuthenticationResponse.prototype.toObject = function(opt_includeInstance) {
  return proto.santiago.web.authentication.AuthenticationResponse.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.santiago.web.authentication.AuthenticationResponse} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.santiago.web.authentication.AuthenticationResponse.toObject = function(includeInstance, msg) {
  var f, obj = {
    sessionid: jspb.Message.getFieldWithDefault(msg, 1, ""),
    player: (f = msg.getPlayer()) && proto.santiago.web.authentication.Player.toObject(includeInstance, f),
    timetravel: (f = msg.getTimetravel()) && proto.santiago.web.authentication.TimeTravel.toObject(includeInstance, f),
    protocolversionoverride: (f = msg.getProtocolversionoverride()) && proto.santiago.web.authentication.ProtocolVersionOverride.toObject(includeInstance, f),
    patchversion: jspb.Message.getFieldWithDefault(msg, 5, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.santiago.web.authentication.AuthenticationResponse}
 */
proto.santiago.web.authentication.AuthenticationResponse.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.santiago.web.authentication.AuthenticationResponse;
  return proto.santiago.web.authentication.AuthenticationResponse.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.santiago.web.authentication.AuthenticationResponse} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.santiago.web.authentication.AuthenticationResponse}
 */
proto.santiago.web.authentication.AuthenticationResponse.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setSessionid(value);
      break;
    case 2:
      var value = new proto.santiago.web.authentication.Player;
      reader.readMessage(value,proto.santiago.web.authentication.Player.deserializeBinaryFromReader);
      msg.setPlayer(value);
      break;
    case 3:
      var value = new proto.santiago.web.authentication.TimeTravel;
      reader.readMessage(value,proto.santiago.web.authentication.TimeTravel.deserializeBinaryFromReader);
      msg.setTimetravel(value);
      break;
    case 4:
      var value = new proto.santiago.web.authentication.ProtocolVersionOverride;
      reader.readMessage(value,proto.santiago.web.authentication.ProtocolVersionOverride.deserializeBinaryFromReader);
      msg.setProtocolversionoverride(value);
      break;
    case 5:
      var value = /** @type {string} */ (reader.readString());
      msg.setPatchversion(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.santiago.web.authentication.AuthenticationResponse.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.santiago.web.authentication.AuthenticationResponse.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.santiago.web.authentication.AuthenticationResponse} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.santiago.web.authentication.AuthenticationResponse.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getSessionid();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getPlayer();
  if (f != null) {
    writer.writeMessage(
      2,
      f,
      proto.santiago.web.authentication.Player.serializeBinaryToWriter
    );
  }
  f = message.getTimetravel();
  if (f != null) {
    writer.writeMessage(
      3,
      f,
      proto.santiago.web.authentication.TimeTravel.serializeBinaryToWriter
    );
  }
  f = message.getProtocolversionoverride();
  if (f != null) {
    writer.writeMessage(
      4,
      f,
      proto.santiago.web.authentication.ProtocolVersionOverride.serializeBinaryToWriter
    );
  }
  f = message.getPatchversion();
  if (f.length > 0) {
    writer.writeString(
      5,
      f
    );
  }
};


/**
 * optional string sessionId = 1;
 * @return {string}
 */
proto.santiago.web.authentication.AuthenticationResponse.prototype.getSessionid = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.santiago.web.authentication.AuthenticationResponse} returns this
 */
proto.santiago.web.authentication.AuthenticationResponse.prototype.setSessionid = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional Player player = 2;
 * @return {?proto.santiago.web.authentication.Player}
 */
proto.santiago.web.authentication.AuthenticationResponse.prototype.getPlayer = function() {
  return /** @type{?proto.santiago.web.authentication.Player} */ (
    jspb.Message.getWrapperField(this, proto.santiago.web.authentication.Player, 2));
};


/**
 * @param {?proto.santiago.web.authentication.Player|undefined} value
 * @return {!proto.santiago.web.authentication.AuthenticationResponse} returns this
*/
proto.santiago.web.authentication.AuthenticationResponse.prototype.setPlayer = function(value) {
  return jspb.Message.setWrapperField(this, 2, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.santiago.web.authentication.AuthenticationResponse} returns this
 */
proto.santiago.web.authentication.AuthenticationResponse.prototype.clearPlayer = function() {
  return this.setPlayer(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.santiago.web.authentication.AuthenticationResponse.prototype.hasPlayer = function() {
  return jspb.Message.getField(this, 2) != null;
};


/**
 * optional TimeTravel timeTravel = 3;
 * @return {?proto.santiago.web.authentication.TimeTravel}
 */
proto.santiago.web.authentication.AuthenticationResponse.prototype.getTimetravel = function() {
  return /** @type{?proto.santiago.web.authentication.TimeTravel} */ (
    jspb.Message.getWrapperField(this, proto.santiago.web.authentication.TimeTravel, 3));
};


/**
 * @param {?proto.santiago.web.authentication.TimeTravel|undefined} value
 * @return {!proto.santiago.web.authentication.AuthenticationResponse} returns this
*/
proto.santiago.web.authentication.AuthenticationResponse.prototype.setTimetravel = function(value) {
  return jspb.Message.setWrapperField(this, 3, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.santiago.web.authentication.AuthenticationResponse} returns this
 */
proto.santiago.web.authentication.AuthenticationResponse.prototype.clearTimetravel = function() {
  return this.setTimetravel(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.santiago.web.authentication.AuthenticationResponse.prototype.hasTimetravel = function() {
  return jspb.Message.getField(this, 3) != null;
};


/**
 * optional ProtocolVersionOverride protocolVersionOverride = 4;
 * @return {?proto.santiago.web.authentication.ProtocolVersionOverride}
 */
proto.santiago.web.authentication.AuthenticationResponse.prototype.getProtocolversionoverride = function() {
  return /** @type{?proto.santiago.web.authentication.ProtocolVersionOverride} */ (
    jspb.Message.getWrapperField(this, proto.santiago.web.authentication.ProtocolVersionOverride, 4));
};


/**
 * @param {?proto.santiago.web.authentication.ProtocolVersionOverride|undefined} value
 * @return {!proto.santiago.web.authentication.AuthenticationResponse} returns this
*/
proto.santiago.web.authentication.AuthenticationResponse.prototype.setProtocolversionoverride = function(value) {
  return jspb.Message.setWrapperField(this, 4, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.santiago.web.authentication.AuthenticationResponse} returns this
 */
proto.santiago.web.authentication.AuthenticationResponse.prototype.clearProtocolversionoverride = function() {
  return this.setProtocolversionoverride(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.santiago.web.authentication.AuthenticationResponse.prototype.hasProtocolversionoverride = function() {
  return jspb.Message.getField(this, 4) != null;
};


/**
 * optional string patchVersion = 5;
 * @return {string}
 */
proto.santiago.web.authentication.AuthenticationResponse.prototype.getPatchversion = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 5, ""));
};


/**
 * @param {string} value
 * @return {!proto.santiago.web.authentication.AuthenticationResponse} returns this
 */
proto.santiago.web.authentication.AuthenticationResponse.prototype.setPatchversion = function(value) {
  return jspb.Message.setProto3StringField(this, 5, value);
};


/**
 * @enum {number}
 */
proto.santiago.web.authentication.Platform = {
  UNKNOWN: 0,
  PC: 1,
  PS4: 2,
  XBOXONE: 3,
  PS5: 4,
  XBSX: 5,
  COMMON: 6,
  STEAM: 7
};

/**
 * @enum {number}
 */
proto.santiago.web.authentication.Reason = {
  NONE: 0,
  SYNC: 1
};

goog.object.extend(exports, proto.santiago.web.authentication);
