// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.8.3
//   protoc               v3.19.1
// source: localization.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";
import type { CallContext, CallOptions } from "nice-grpc-common";

export const protobufPackage = "santiago.web.localization";

export interface SidList {
  sids: string[];
}

export interface CategoryIdList {
  ids: number[];
}

export interface SubCategoryIdList {
  ids: number[];
}

export interface TranslationsQuery {
  sidList?: SidList | undefined;
  categoryIdList?: CategoryIdList | undefined;
  subCategoryIdList?: SubCategoryIdList | undefined;
}

export interface LocalizedText {
  sid: string;
  localizedText: string;
  categoryId: number;
}

export interface Timestamp {
  seconds: number;
  nanos: number;
}

export interface GetTranslationsRequest {
  translationsQuery: TranslationsQuery | undefined;
  locale: string;
  fetchFrom?: Timestamp | undefined;
}

export interface GetTranslationsResponse {
  localizedTexts: LocalizedText[];
  fetchedUntil?: Timestamp | undefined;
}

function createBaseSidList(): SidList {
  return { sids: [] };
}

export const SidList: MessageFns<SidList> = {
  encode(message: SidList, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    for (const v of message.sids) {
      writer.uint32(10).string(v!);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): SidList {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseSidList();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.sids.push(reader.string());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create(base?: DeepPartial<SidList>): SidList {
    return SidList.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<SidList>): SidList {
    const message = createBaseSidList();
    message.sids = object.sids?.map((e) => e) || [];
    return message;
  },
};

function createBaseCategoryIdList(): CategoryIdList {
  return { ids: [] };
}

export const CategoryIdList: MessageFns<CategoryIdList> = {
  encode(message: CategoryIdList, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    writer.uint32(10).fork();
    for (const v of message.ids) {
      writer.int32(v);
    }
    writer.join();
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): CategoryIdList {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseCategoryIdList();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag === 8) {
            message.ids.push(reader.int32());

            continue;
          }

          if (tag === 10) {
            const end2 = reader.uint32() + reader.pos;
            while (reader.pos < end2) {
              message.ids.push(reader.int32());
            }

            continue;
          }

          break;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create(base?: DeepPartial<CategoryIdList>): CategoryIdList {
    return CategoryIdList.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<CategoryIdList>): CategoryIdList {
    const message = createBaseCategoryIdList();
    message.ids = object.ids?.map((e) => e) || [];
    return message;
  },
};

function createBaseSubCategoryIdList(): SubCategoryIdList {
  return { ids: [] };
}

export const SubCategoryIdList: MessageFns<SubCategoryIdList> = {
  encode(message: SubCategoryIdList, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    writer.uint32(10).fork();
    for (const v of message.ids) {
      writer.int32(v);
    }
    writer.join();
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): SubCategoryIdList {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseSubCategoryIdList();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag === 8) {
            message.ids.push(reader.int32());

            continue;
          }

          if (tag === 10) {
            const end2 = reader.uint32() + reader.pos;
            while (reader.pos < end2) {
              message.ids.push(reader.int32());
            }

            continue;
          }

          break;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create(base?: DeepPartial<SubCategoryIdList>): SubCategoryIdList {
    return SubCategoryIdList.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<SubCategoryIdList>): SubCategoryIdList {
    const message = createBaseSubCategoryIdList();
    message.ids = object.ids?.map((e) => e) || [];
    return message;
  },
};

function createBaseTranslationsQuery(): TranslationsQuery {
  return { sidList: undefined, categoryIdList: undefined, subCategoryIdList: undefined };
}

export const TranslationsQuery: MessageFns<TranslationsQuery> = {
  encode(message: TranslationsQuery, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.sidList !== undefined) {
      SidList.encode(message.sidList, writer.uint32(10).fork()).join();
    }
    if (message.categoryIdList !== undefined) {
      CategoryIdList.encode(message.categoryIdList, writer.uint32(18).fork()).join();
    }
    if (message.subCategoryIdList !== undefined) {
      SubCategoryIdList.encode(message.subCategoryIdList, writer.uint32(26).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): TranslationsQuery {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseTranslationsQuery();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.sidList = SidList.decode(reader, reader.uint32());
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.categoryIdList = CategoryIdList.decode(reader, reader.uint32());
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.subCategoryIdList = SubCategoryIdList.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create(base?: DeepPartial<TranslationsQuery>): TranslationsQuery {
    return TranslationsQuery.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<TranslationsQuery>): TranslationsQuery {
    const message = createBaseTranslationsQuery();
    message.sidList = (object.sidList !== undefined && object.sidList !== null)
      ? SidList.fromPartial(object.sidList)
      : undefined;
    message.categoryIdList = (object.categoryIdList !== undefined && object.categoryIdList !== null)
      ? CategoryIdList.fromPartial(object.categoryIdList)
      : undefined;
    message.subCategoryIdList = (object.subCategoryIdList !== undefined && object.subCategoryIdList !== null)
      ? SubCategoryIdList.fromPartial(object.subCategoryIdList)
      : undefined;
    return message;
  },
};

function createBaseLocalizedText(): LocalizedText {
  return { sid: "", localizedText: "", categoryId: 0 };
}

export const LocalizedText: MessageFns<LocalizedText> = {
  encode(message: LocalizedText, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.sid !== "") {
      writer.uint32(10).string(message.sid);
    }
    if (message.localizedText !== "") {
      writer.uint32(18).string(message.localizedText);
    }
    if (message.categoryId !== 0) {
      writer.uint32(24).int32(message.categoryId);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): LocalizedText {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseLocalizedText();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.sid = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.localizedText = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.categoryId = reader.int32();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create(base?: DeepPartial<LocalizedText>): LocalizedText {
    return LocalizedText.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<LocalizedText>): LocalizedText {
    const message = createBaseLocalizedText();
    message.sid = object.sid ?? "";
    message.localizedText = object.localizedText ?? "";
    message.categoryId = object.categoryId ?? 0;
    return message;
  },
};

function createBaseTimestamp(): Timestamp {
  return { seconds: 0, nanos: 0 };
}

export const Timestamp: MessageFns<Timestamp> = {
  encode(message: Timestamp, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.seconds !== 0) {
      writer.uint32(8).int64(message.seconds);
    }
    if (message.nanos !== 0) {
      writer.uint32(16).int32(message.nanos);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): Timestamp {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseTimestamp();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.seconds = longToNumber(reader.int64());
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.nanos = reader.int32();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create(base?: DeepPartial<Timestamp>): Timestamp {
    return Timestamp.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<Timestamp>): Timestamp {
    const message = createBaseTimestamp();
    message.seconds = object.seconds ?? 0;
    message.nanos = object.nanos ?? 0;
    return message;
  },
};

function createBaseGetTranslationsRequest(): GetTranslationsRequest {
  return { translationsQuery: undefined, locale: "", fetchFrom: undefined };
}

export const GetTranslationsRequest: MessageFns<GetTranslationsRequest> = {
  encode(message: GetTranslationsRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.translationsQuery !== undefined) {
      TranslationsQuery.encode(message.translationsQuery, writer.uint32(10).fork()).join();
    }
    if (message.locale !== "") {
      writer.uint32(18).string(message.locale);
    }
    if (message.fetchFrom !== undefined) {
      Timestamp.encode(message.fetchFrom, writer.uint32(26).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): GetTranslationsRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseGetTranslationsRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.translationsQuery = TranslationsQuery.decode(reader, reader.uint32());
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.locale = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.fetchFrom = Timestamp.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create(base?: DeepPartial<GetTranslationsRequest>): GetTranslationsRequest {
    return GetTranslationsRequest.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<GetTranslationsRequest>): GetTranslationsRequest {
    const message = createBaseGetTranslationsRequest();
    message.translationsQuery = (object.translationsQuery !== undefined && object.translationsQuery !== null)
      ? TranslationsQuery.fromPartial(object.translationsQuery)
      : undefined;
    message.locale = object.locale ?? "";
    message.fetchFrom = (object.fetchFrom !== undefined && object.fetchFrom !== null)
      ? Timestamp.fromPartial(object.fetchFrom)
      : undefined;
    return message;
  },
};

function createBaseGetTranslationsResponse(): GetTranslationsResponse {
  return { localizedTexts: [], fetchedUntil: undefined };
}

export const GetTranslationsResponse: MessageFns<GetTranslationsResponse> = {
  encode(message: GetTranslationsResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    for (const v of message.localizedTexts) {
      LocalizedText.encode(v!, writer.uint32(10).fork()).join();
    }
    if (message.fetchedUntil !== undefined) {
      Timestamp.encode(message.fetchedUntil, writer.uint32(18).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): GetTranslationsResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseGetTranslationsResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.localizedTexts.push(LocalizedText.decode(reader, reader.uint32()));
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.fetchedUntil = Timestamp.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create(base?: DeepPartial<GetTranslationsResponse>): GetTranslationsResponse {
    return GetTranslationsResponse.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<GetTranslationsResponse>): GetTranslationsResponse {
    const message = createBaseGetTranslationsResponse();
    message.localizedTexts = object.localizedTexts?.map((e) => LocalizedText.fromPartial(e)) || [];
    message.fetchedUntil = (object.fetchedUntil !== undefined && object.fetchedUntil !== null)
      ? Timestamp.fromPartial(object.fetchedUntil)
      : undefined;
    return message;
  },
};

export type ClientLocalizationDefinition = typeof ClientLocalizationDefinition;
export const ClientLocalizationDefinition = {
  name: "ClientLocalization",
  fullName: "santiago.web.localization.ClientLocalization",
  methods: {
    getTranslations: {
      name: "getTranslations",
      requestType: GetTranslationsRequest,
      requestStream: false,
      responseType: GetTranslationsResponse,
      responseStream: false,
      options: {},
    },
  },
} as const;

export interface ClientLocalizationServiceImplementation<CallContextExt = {}> {
  getTranslations(
    request: GetTranslationsRequest,
    context: CallContext & CallContextExt,
  ): Promise<DeepPartial<GetTranslationsResponse>>;
}

export interface ClientLocalizationClient<CallOptionsExt = {}> {
  getTranslations(
    request: DeepPartial<GetTranslationsRequest>,
    options?: CallOptions & CallOptionsExt,
  ): Promise<GetTranslationsResponse>;
}

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

function longToNumber(int64: { toString(): string }): number {
  const num = globalThis.Number(int64.toString());
  if (num > globalThis.Number.MAX_SAFE_INTEGER) {
    throw new globalThis.Error("Value is larger than Number.MAX_SAFE_INTEGER");
  }
  if (num < globalThis.Number.MIN_SAFE_INTEGER) {
    throw new globalThis.Error("Value is smaller than Number.MIN_SAFE_INTEGER");
  }
  return num;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  create(base?: DeepPartial<T>): T;
  fromPartial(object: DeepPartial<T>): T;
}
