// source: reporting.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {missingRequire} reports error on implicit type usages.
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!
/* eslint-disable */
// @ts-nocheck

var jspb = require('google-protobuf');
var goog = jspb;
var global = (function() { return this || window || global || self || Function('return this')(); }).call(null);

goog.exportSymbol('proto.santiago.web.reporting.CreatePetitionError', null, global);
goog.exportSymbol('proto.santiago.web.reporting.CreatePetitionSuccess', null, global);
goog.exportSymbol('proto.santiago.web.reporting.Platform', null, global);
goog.exportSymbol('proto.santiago.web.reporting.Player', null, global);
goog.exportSymbol('proto.santiago.web.reporting.ReportExperienceRequest', null, global);
goog.exportSymbol('proto.santiago.web.reporting.ReportPlayerRequest', null, global);
goog.exportSymbol('proto.santiago.web.reporting.ReportingErrorType', null, global);
goog.exportSymbol('proto.santiago.web.reporting.ReportingResponse', null, global);
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.santiago.web.reporting.Player = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.santiago.web.reporting.Player, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.santiago.web.reporting.Player.displayName = 'proto.santiago.web.reporting.Player';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.santiago.web.reporting.ReportPlayerRequest = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.santiago.web.reporting.ReportPlayerRequest, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.santiago.web.reporting.ReportPlayerRequest.displayName = 'proto.santiago.web.reporting.ReportPlayerRequest';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.santiago.web.reporting.ReportExperienceRequest = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.santiago.web.reporting.ReportExperienceRequest, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.santiago.web.reporting.ReportExperienceRequest.displayName = 'proto.santiago.web.reporting.ReportExperienceRequest';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.santiago.web.reporting.ReportingResponse = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.santiago.web.reporting.ReportingResponse, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.santiago.web.reporting.ReportingResponse.displayName = 'proto.santiago.web.reporting.ReportingResponse';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.santiago.web.reporting.CreatePetitionSuccess = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.santiago.web.reporting.CreatePetitionSuccess, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.santiago.web.reporting.CreatePetitionSuccess.displayName = 'proto.santiago.web.reporting.CreatePetitionSuccess';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.santiago.web.reporting.CreatePetitionError = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.santiago.web.reporting.CreatePetitionError, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.santiago.web.reporting.CreatePetitionError.displayName = 'proto.santiago.web.reporting.CreatePetitionError';
}



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.santiago.web.reporting.Player.prototype.toObject = function(opt_includeInstance) {
  return proto.santiago.web.reporting.Player.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.santiago.web.reporting.Player} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.santiago.web.reporting.Player.toObject = function(includeInstance, msg) {
  var f, obj = {
    nucleusid: jspb.Message.getFieldWithDefault(msg, 1, 0),
    personaid: jspb.Message.getFieldWithDefault(msg, 2, 0),
    platform: jspb.Message.getFieldWithDefault(msg, 3, 0)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.santiago.web.reporting.Player}
 */
proto.santiago.web.reporting.Player.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.santiago.web.reporting.Player;
  return proto.santiago.web.reporting.Player.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.santiago.web.reporting.Player} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.santiago.web.reporting.Player}
 */
proto.santiago.web.reporting.Player.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {number} */ (reader.readInt64());
      msg.setNucleusid(value);
      break;
    case 2:
      var value = /** @type {number} */ (reader.readInt64());
      msg.setPersonaid(value);
      break;
    case 3:
      var value = /** @type {!proto.santiago.web.reporting.Platform} */ (reader.readEnum());
      msg.setPlatform(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.santiago.web.reporting.Player.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.santiago.web.reporting.Player.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.santiago.web.reporting.Player} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.santiago.web.reporting.Player.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getNucleusid();
  if (f !== 0) {
    writer.writeInt64(
      1,
      f
    );
  }
  f = message.getPersonaid();
  if (f !== 0) {
    writer.writeInt64(
      2,
      f
    );
  }
  f = message.getPlatform();
  if (f !== 0.0) {
    writer.writeEnum(
      3,
      f
    );
  }
};


/**
 * optional int64 nucleusId = 1;
 * @return {number}
 */
proto.santiago.web.reporting.Player.prototype.getNucleusid = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 1, 0));
};


/**
 * @param {number} value
 * @return {!proto.santiago.web.reporting.Player} returns this
 */
proto.santiago.web.reporting.Player.prototype.setNucleusid = function(value) {
  return jspb.Message.setProto3IntField(this, 1, value);
};


/**
 * optional int64 personaId = 2;
 * @return {number}
 */
proto.santiago.web.reporting.Player.prototype.getPersonaid = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 2, 0));
};


/**
 * @param {number} value
 * @return {!proto.santiago.web.reporting.Player} returns this
 */
proto.santiago.web.reporting.Player.prototype.setPersonaid = function(value) {
  return jspb.Message.setProto3IntField(this, 2, value);
};


/**
 * optional Platform platform = 3;
 * @return {!proto.santiago.web.reporting.Platform}
 */
proto.santiago.web.reporting.Player.prototype.getPlatform = function() {
  return /** @type {!proto.santiago.web.reporting.Platform} */ (jspb.Message.getFieldWithDefault(this, 3, 0));
};


/**
 * @param {!proto.santiago.web.reporting.Platform} value
 * @return {!proto.santiago.web.reporting.Player} returns this
 */
proto.santiago.web.reporting.Player.prototype.setPlatform = function(value) {
  return jspb.Message.setProto3EnumField(this, 3, value);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.santiago.web.reporting.ReportPlayerRequest.prototype.toObject = function(opt_includeInstance) {
  return proto.santiago.web.reporting.ReportPlayerRequest.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.santiago.web.reporting.ReportPlayerRequest} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.santiago.web.reporting.ReportPlayerRequest.toObject = function(includeInstance, msg) {
  var f, obj = {
    offendingplayer: (f = msg.getOffendingplayer()) && proto.santiago.web.reporting.Player.toObject(includeInstance, f),
    subject: jspb.Message.getFieldWithDefault(msg, 2, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.santiago.web.reporting.ReportPlayerRequest}
 */
proto.santiago.web.reporting.ReportPlayerRequest.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.santiago.web.reporting.ReportPlayerRequest;
  return proto.santiago.web.reporting.ReportPlayerRequest.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.santiago.web.reporting.ReportPlayerRequest} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.santiago.web.reporting.ReportPlayerRequest}
 */
proto.santiago.web.reporting.ReportPlayerRequest.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new proto.santiago.web.reporting.Player;
      reader.readMessage(value,proto.santiago.web.reporting.Player.deserializeBinaryFromReader);
      msg.setOffendingplayer(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setSubject(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.santiago.web.reporting.ReportPlayerRequest.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.santiago.web.reporting.ReportPlayerRequest.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.santiago.web.reporting.ReportPlayerRequest} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.santiago.web.reporting.ReportPlayerRequest.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getOffendingplayer();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      proto.santiago.web.reporting.Player.serializeBinaryToWriter
    );
  }
  f = /** @type {string} */ (jspb.Message.getField(message, 2));
  if (f != null) {
    writer.writeString(
      2,
      f
    );
  }
};


/**
 * optional Player offendingPlayer = 1;
 * @return {?proto.santiago.web.reporting.Player}
 */
proto.santiago.web.reporting.ReportPlayerRequest.prototype.getOffendingplayer = function() {
  return /** @type{?proto.santiago.web.reporting.Player} */ (
    jspb.Message.getWrapperField(this, proto.santiago.web.reporting.Player, 1));
};


/**
 * @param {?proto.santiago.web.reporting.Player|undefined} value
 * @return {!proto.santiago.web.reporting.ReportPlayerRequest} returns this
*/
proto.santiago.web.reporting.ReportPlayerRequest.prototype.setOffendingplayer = function(value) {
  return jspb.Message.setWrapperField(this, 1, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.santiago.web.reporting.ReportPlayerRequest} returns this
 */
proto.santiago.web.reporting.ReportPlayerRequest.prototype.clearOffendingplayer = function() {
  return this.setOffendingplayer(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.santiago.web.reporting.ReportPlayerRequest.prototype.hasOffendingplayer = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * optional string subject = 2;
 * @return {string}
 */
proto.santiago.web.reporting.ReportPlayerRequest.prototype.getSubject = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * @param {string} value
 * @return {!proto.santiago.web.reporting.ReportPlayerRequest} returns this
 */
proto.santiago.web.reporting.ReportPlayerRequest.prototype.setSubject = function(value) {
  return jspb.Message.setField(this, 2, value);
};


/**
 * Clears the field making it undefined.
 * @return {!proto.santiago.web.reporting.ReportPlayerRequest} returns this
 */
proto.santiago.web.reporting.ReportPlayerRequest.prototype.clearSubject = function() {
  return jspb.Message.setField(this, 2, undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.santiago.web.reporting.ReportPlayerRequest.prototype.hasSubject = function() {
  return jspb.Message.getField(this, 2) != null;
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.santiago.web.reporting.ReportExperienceRequest.prototype.toObject = function(opt_includeInstance) {
  return proto.santiago.web.reporting.ReportExperienceRequest.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.santiago.web.reporting.ReportExperienceRequest} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.santiago.web.reporting.ReportExperienceRequest.toObject = function(includeInstance, msg) {
  var f, obj = {
    experienceid: jspb.Message.getFieldWithDefault(msg, 1, ""),
    subject: jspb.Message.getFieldWithDefault(msg, 2, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.santiago.web.reporting.ReportExperienceRequest}
 */
proto.santiago.web.reporting.ReportExperienceRequest.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.santiago.web.reporting.ReportExperienceRequest;
  return proto.santiago.web.reporting.ReportExperienceRequest.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.santiago.web.reporting.ReportExperienceRequest} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.santiago.web.reporting.ReportExperienceRequest}
 */
proto.santiago.web.reporting.ReportExperienceRequest.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setExperienceid(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setSubject(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.santiago.web.reporting.ReportExperienceRequest.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.santiago.web.reporting.ReportExperienceRequest.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.santiago.web.reporting.ReportExperienceRequest} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.santiago.web.reporting.ReportExperienceRequest.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getExperienceid();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = /** @type {string} */ (jspb.Message.getField(message, 2));
  if (f != null) {
    writer.writeString(
      2,
      f
    );
  }
};


/**
 * optional string experienceId = 1;
 * @return {string}
 */
proto.santiago.web.reporting.ReportExperienceRequest.prototype.getExperienceid = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.santiago.web.reporting.ReportExperienceRequest} returns this
 */
proto.santiago.web.reporting.ReportExperienceRequest.prototype.setExperienceid = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional string subject = 2;
 * @return {string}
 */
proto.santiago.web.reporting.ReportExperienceRequest.prototype.getSubject = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * @param {string} value
 * @return {!proto.santiago.web.reporting.ReportExperienceRequest} returns this
 */
proto.santiago.web.reporting.ReportExperienceRequest.prototype.setSubject = function(value) {
  return jspb.Message.setField(this, 2, value);
};


/**
 * Clears the field making it undefined.
 * @return {!proto.santiago.web.reporting.ReportExperienceRequest} returns this
 */
proto.santiago.web.reporting.ReportExperienceRequest.prototype.clearSubject = function() {
  return jspb.Message.setField(this, 2, undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.santiago.web.reporting.ReportExperienceRequest.prototype.hasSubject = function() {
  return jspb.Message.getField(this, 2) != null;
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.santiago.web.reporting.ReportingResponse.prototype.toObject = function(opt_includeInstance) {
  return proto.santiago.web.reporting.ReportingResponse.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.santiago.web.reporting.ReportingResponse} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.santiago.web.reporting.ReportingResponse.toObject = function(includeInstance, msg) {
  var f, obj = {
    success: (f = msg.getSuccess()) && proto.santiago.web.reporting.CreatePetitionSuccess.toObject(includeInstance, f),
    error: (f = msg.getError()) && proto.santiago.web.reporting.CreatePetitionError.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.santiago.web.reporting.ReportingResponse}
 */
proto.santiago.web.reporting.ReportingResponse.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.santiago.web.reporting.ReportingResponse;
  return proto.santiago.web.reporting.ReportingResponse.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.santiago.web.reporting.ReportingResponse} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.santiago.web.reporting.ReportingResponse}
 */
proto.santiago.web.reporting.ReportingResponse.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new proto.santiago.web.reporting.CreatePetitionSuccess;
      reader.readMessage(value,proto.santiago.web.reporting.CreatePetitionSuccess.deserializeBinaryFromReader);
      msg.setSuccess(value);
      break;
    case 2:
      var value = new proto.santiago.web.reporting.CreatePetitionError;
      reader.readMessage(value,proto.santiago.web.reporting.CreatePetitionError.deserializeBinaryFromReader);
      msg.setError(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.santiago.web.reporting.ReportingResponse.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.santiago.web.reporting.ReportingResponse.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.santiago.web.reporting.ReportingResponse} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.santiago.web.reporting.ReportingResponse.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getSuccess();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      proto.santiago.web.reporting.CreatePetitionSuccess.serializeBinaryToWriter
    );
  }
  f = message.getError();
  if (f != null) {
    writer.writeMessage(
      2,
      f,
      proto.santiago.web.reporting.CreatePetitionError.serializeBinaryToWriter
    );
  }
};


/**
 * optional CreatePetitionSuccess success = 1;
 * @return {?proto.santiago.web.reporting.CreatePetitionSuccess}
 */
proto.santiago.web.reporting.ReportingResponse.prototype.getSuccess = function() {
  return /** @type{?proto.santiago.web.reporting.CreatePetitionSuccess} */ (
    jspb.Message.getWrapperField(this, proto.santiago.web.reporting.CreatePetitionSuccess, 1));
};


/**
 * @param {?proto.santiago.web.reporting.CreatePetitionSuccess|undefined} value
 * @return {!proto.santiago.web.reporting.ReportingResponse} returns this
*/
proto.santiago.web.reporting.ReportingResponse.prototype.setSuccess = function(value) {
  return jspb.Message.setWrapperField(this, 1, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.santiago.web.reporting.ReportingResponse} returns this
 */
proto.santiago.web.reporting.ReportingResponse.prototype.clearSuccess = function() {
  return this.setSuccess(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.santiago.web.reporting.ReportingResponse.prototype.hasSuccess = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * optional CreatePetitionError error = 2;
 * @return {?proto.santiago.web.reporting.CreatePetitionError}
 */
proto.santiago.web.reporting.ReportingResponse.prototype.getError = function() {
  return /** @type{?proto.santiago.web.reporting.CreatePetitionError} */ (
    jspb.Message.getWrapperField(this, proto.santiago.web.reporting.CreatePetitionError, 2));
};


/**
 * @param {?proto.santiago.web.reporting.CreatePetitionError|undefined} value
 * @return {!proto.santiago.web.reporting.ReportingResponse} returns this
*/
proto.santiago.web.reporting.ReportingResponse.prototype.setError = function(value) {
  return jspb.Message.setWrapperField(this, 2, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.santiago.web.reporting.ReportingResponse} returns this
 */
proto.santiago.web.reporting.ReportingResponse.prototype.clearError = function() {
  return this.setError(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.santiago.web.reporting.ReportingResponse.prototype.hasError = function() {
  return jspb.Message.getField(this, 2) != null;
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.santiago.web.reporting.CreatePetitionSuccess.prototype.toObject = function(opt_includeInstance) {
  return proto.santiago.web.reporting.CreatePetitionSuccess.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.santiago.web.reporting.CreatePetitionSuccess} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.santiago.web.reporting.CreatePetitionSuccess.toObject = function(includeInstance, msg) {
  var f, obj = {
    petitionid: jspb.Message.getFieldWithDefault(msg, 1, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.santiago.web.reporting.CreatePetitionSuccess}
 */
proto.santiago.web.reporting.CreatePetitionSuccess.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.santiago.web.reporting.CreatePetitionSuccess;
  return proto.santiago.web.reporting.CreatePetitionSuccess.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.santiago.web.reporting.CreatePetitionSuccess} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.santiago.web.reporting.CreatePetitionSuccess}
 */
proto.santiago.web.reporting.CreatePetitionSuccess.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setPetitionid(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.santiago.web.reporting.CreatePetitionSuccess.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.santiago.web.reporting.CreatePetitionSuccess.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.santiago.web.reporting.CreatePetitionSuccess} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.santiago.web.reporting.CreatePetitionSuccess.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getPetitionid();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
};


/**
 * optional string petitionId = 1;
 * @return {string}
 */
proto.santiago.web.reporting.CreatePetitionSuccess.prototype.getPetitionid = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.santiago.web.reporting.CreatePetitionSuccess} returns this
 */
proto.santiago.web.reporting.CreatePetitionSuccess.prototype.setPetitionid = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.santiago.web.reporting.CreatePetitionError.prototype.toObject = function(opt_includeInstance) {
  return proto.santiago.web.reporting.CreatePetitionError.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.santiago.web.reporting.CreatePetitionError} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.santiago.web.reporting.CreatePetitionError.toObject = function(includeInstance, msg) {
  var f, obj = {
    errortype: jspb.Message.getFieldWithDefault(msg, 1, 0),
    errormessage: jspb.Message.getFieldWithDefault(msg, 2, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.santiago.web.reporting.CreatePetitionError}
 */
proto.santiago.web.reporting.CreatePetitionError.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.santiago.web.reporting.CreatePetitionError;
  return proto.santiago.web.reporting.CreatePetitionError.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.santiago.web.reporting.CreatePetitionError} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.santiago.web.reporting.CreatePetitionError}
 */
proto.santiago.web.reporting.CreatePetitionError.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {!proto.santiago.web.reporting.ReportingErrorType} */ (reader.readEnum());
      msg.setErrortype(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setErrormessage(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.santiago.web.reporting.CreatePetitionError.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.santiago.web.reporting.CreatePetitionError.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.santiago.web.reporting.CreatePetitionError} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.santiago.web.reporting.CreatePetitionError.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getErrortype();
  if (f !== 0.0) {
    writer.writeEnum(
      1,
      f
    );
  }
  f = message.getErrormessage();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
};


/**
 * optional ReportingErrorType errorType = 1;
 * @return {!proto.santiago.web.reporting.ReportingErrorType}
 */
proto.santiago.web.reporting.CreatePetitionError.prototype.getErrortype = function() {
  return /** @type {!proto.santiago.web.reporting.ReportingErrorType} */ (jspb.Message.getFieldWithDefault(this, 1, 0));
};


/**
 * @param {!proto.santiago.web.reporting.ReportingErrorType} value
 * @return {!proto.santiago.web.reporting.CreatePetitionError} returns this
 */
proto.santiago.web.reporting.CreatePetitionError.prototype.setErrortype = function(value) {
  return jspb.Message.setProto3EnumField(this, 1, value);
};


/**
 * optional string errorMessage = 2;
 * @return {string}
 */
proto.santiago.web.reporting.CreatePetitionError.prototype.getErrormessage = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * @param {string} value
 * @return {!proto.santiago.web.reporting.CreatePetitionError} returns this
 */
proto.santiago.web.reporting.CreatePetitionError.prototype.setErrormessage = function(value) {
  return jspb.Message.setProto3StringField(this, 2, value);
};


/**
 * @enum {number}
 */
proto.santiago.web.reporting.Platform = {
  UNKNOWN: 0,
  PC: 1,
  PS4: 2,
  XBOXONE: 3,
  PS5: 4,
  XBSX: 5,
  COMMON: 6,
  STEAM: 7
};

/**
 * @enum {number}
 */
proto.santiago.web.reporting.ReportingErrorType = {
  ERROR_TYPES_GENERIC_SERVICE_FAILURE: 0,
  ERROR_TYPES_GENERIC_BUSINESS_FAILURE: 1,
  ERROR_TYPES_INVALID_ARGUMENT: 2,
  ERROR_TYPES_RATE_LIMITED: 3
};

goog.object.extend(exports, proto.santiago.web.reporting);
