// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.8.3
//   protoc               v3.19.1
// source: reporting.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";
import type { CallContext, CallOptions } from "nice-grpc-common";

export const protobufPackage = "santiago.web.reporting";

export enum Platform {
  UNKNOWN = 0,
  /** PC - PC - EA App */
  PC = 1,
  PS4 = 2,
  XBOXONE = 3,
  PS5 = 4,
  XBSX = 5,
  /** COMMON - COMMON - Used for requests that includes a cross-platform payload */
  COMMON = 6,
  STEAM = 7,
  UNRECOGNIZED = -1,
}

export enum ReportingErrorType {
  ERROR_TYPES_GENERIC_SERVICE_FAILURE = 0,
  ERROR_TYPES_GENERIC_BUSINESS_FAILURE = 1,
  ERROR_TYPES_INVALID_ARGUMENT = 2,
  ERROR_TYPES_RATE_LIMITED = 3,
  UNRECOGNIZED = -1,
}

export interface Player {
  nucleusId: number;
  personaId: number;
  platform: Platform;
}

export interface ReportPlayerRequest {
  offendingPlayer?: Player | undefined;
  subject?: string | undefined;
}

export interface ReportExperienceRequest {
  experienceId: string;
  subject?: string | undefined;
}

export interface ReportingResponse {
  success?: CreatePetitionSuccess | undefined;
  error?: CreatePetitionError | undefined;
}

export interface CreatePetitionSuccess {
  petitionId: string;
}

export interface CreatePetitionError {
  errorType: ReportingErrorType;
  errorMessage: string;
}

function createBasePlayer(): Player {
  return { nucleusId: 0, personaId: 0, platform: 0 };
}

export const Player: MessageFns<Player> = {
  encode(message: Player, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.nucleusId !== 0) {
      writer.uint32(8).int64(message.nucleusId);
    }
    if (message.personaId !== 0) {
      writer.uint32(16).int64(message.personaId);
    }
    if (message.platform !== 0) {
      writer.uint32(24).int32(message.platform);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): Player {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBasePlayer();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.nucleusId = longToNumber(reader.int64());
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.personaId = longToNumber(reader.int64());
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.platform = reader.int32() as any;
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create(base?: DeepPartial<Player>): Player {
    return Player.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<Player>): Player {
    const message = createBasePlayer();
    message.nucleusId = object.nucleusId ?? 0;
    message.personaId = object.personaId ?? 0;
    message.platform = object.platform ?? 0;
    return message;
  },
};

function createBaseReportPlayerRequest(): ReportPlayerRequest {
  return { offendingPlayer: undefined, subject: undefined };
}

export const ReportPlayerRequest: MessageFns<ReportPlayerRequest> = {
  encode(message: ReportPlayerRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.offendingPlayer !== undefined) {
      Player.encode(message.offendingPlayer, writer.uint32(10).fork()).join();
    }
    if (message.subject !== undefined) {
      writer.uint32(18).string(message.subject);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ReportPlayerRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseReportPlayerRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.offendingPlayer = Player.decode(reader, reader.uint32());
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.subject = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create(base?: DeepPartial<ReportPlayerRequest>): ReportPlayerRequest {
    return ReportPlayerRequest.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<ReportPlayerRequest>): ReportPlayerRequest {
    const message = createBaseReportPlayerRequest();
    message.offendingPlayer = (object.offendingPlayer !== undefined && object.offendingPlayer !== null)
      ? Player.fromPartial(object.offendingPlayer)
      : undefined;
    message.subject = object.subject ?? undefined;
    return message;
  },
};

function createBaseReportExperienceRequest(): ReportExperienceRequest {
  return { experienceId: "", subject: undefined };
}

export const ReportExperienceRequest: MessageFns<ReportExperienceRequest> = {
  encode(message: ReportExperienceRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.experienceId !== "") {
      writer.uint32(10).string(message.experienceId);
    }
    if (message.subject !== undefined) {
      writer.uint32(18).string(message.subject);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ReportExperienceRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseReportExperienceRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.experienceId = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.subject = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create(base?: DeepPartial<ReportExperienceRequest>): ReportExperienceRequest {
    return ReportExperienceRequest.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<ReportExperienceRequest>): ReportExperienceRequest {
    const message = createBaseReportExperienceRequest();
    message.experienceId = object.experienceId ?? "";
    message.subject = object.subject ?? undefined;
    return message;
  },
};

function createBaseReportingResponse(): ReportingResponse {
  return { success: undefined, error: undefined };
}

export const ReportingResponse: MessageFns<ReportingResponse> = {
  encode(message: ReportingResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.success !== undefined) {
      CreatePetitionSuccess.encode(message.success, writer.uint32(10).fork()).join();
    }
    if (message.error !== undefined) {
      CreatePetitionError.encode(message.error, writer.uint32(18).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ReportingResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseReportingResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.success = CreatePetitionSuccess.decode(reader, reader.uint32());
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.error = CreatePetitionError.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create(base?: DeepPartial<ReportingResponse>): ReportingResponse {
    return ReportingResponse.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<ReportingResponse>): ReportingResponse {
    const message = createBaseReportingResponse();
    message.success = (object.success !== undefined && object.success !== null)
      ? CreatePetitionSuccess.fromPartial(object.success)
      : undefined;
    message.error = (object.error !== undefined && object.error !== null)
      ? CreatePetitionError.fromPartial(object.error)
      : undefined;
    return message;
  },
};

function createBaseCreatePetitionSuccess(): CreatePetitionSuccess {
  return { petitionId: "" };
}

export const CreatePetitionSuccess: MessageFns<CreatePetitionSuccess> = {
  encode(message: CreatePetitionSuccess, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.petitionId !== "") {
      writer.uint32(10).string(message.petitionId);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): CreatePetitionSuccess {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseCreatePetitionSuccess();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.petitionId = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create(base?: DeepPartial<CreatePetitionSuccess>): CreatePetitionSuccess {
    return CreatePetitionSuccess.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<CreatePetitionSuccess>): CreatePetitionSuccess {
    const message = createBaseCreatePetitionSuccess();
    message.petitionId = object.petitionId ?? "";
    return message;
  },
};

function createBaseCreatePetitionError(): CreatePetitionError {
  return { errorType: 0, errorMessage: "" };
}

export const CreatePetitionError: MessageFns<CreatePetitionError> = {
  encode(message: CreatePetitionError, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.errorType !== 0) {
      writer.uint32(8).int32(message.errorType);
    }
    if (message.errorMessage !== "") {
      writer.uint32(18).string(message.errorMessage);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): CreatePetitionError {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseCreatePetitionError();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.errorType = reader.int32() as any;
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.errorMessage = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create(base?: DeepPartial<CreatePetitionError>): CreatePetitionError {
    return CreatePetitionError.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<CreatePetitionError>): CreatePetitionError {
    const message = createBaseCreatePetitionError();
    message.errorType = object.errorType ?? 0;
    message.errorMessage = object.errorMessage ?? "";
    return message;
  },
};

export type WebReportingDefinition = typeof WebReportingDefinition;
export const WebReportingDefinition = {
  name: "WebReporting",
  fullName: "santiago.web.reporting.WebReporting",
  methods: {
    reportPlayer: {
      name: "ReportPlayer",
      requestType: ReportPlayerRequest,
      requestStream: false,
      responseType: ReportingResponse,
      responseStream: false,
      options: {},
    },
    reportExperience: {
      name: "ReportExperience",
      requestType: ReportExperienceRequest,
      requestStream: false,
      responseType: ReportingResponse,
      responseStream: false,
      options: {},
    },
  },
} as const;

export interface WebReportingServiceImplementation<CallContextExt = {}> {
  reportPlayer(
    request: ReportPlayerRequest,
    context: CallContext & CallContextExt,
  ): Promise<DeepPartial<ReportingResponse>>;
  reportExperience(
    request: ReportExperienceRequest,
    context: CallContext & CallContextExt,
  ): Promise<DeepPartial<ReportingResponse>>;
}

export interface WebReportingClient<CallOptionsExt = {}> {
  reportPlayer(
    request: DeepPartial<ReportPlayerRequest>,
    options?: CallOptions & CallOptionsExt,
  ): Promise<ReportingResponse>;
  reportExperience(
    request: DeepPartial<ReportExperienceRequest>,
    options?: CallOptions & CallOptionsExt,
  ): Promise<ReportingResponse>;
}

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

function longToNumber(int64: { toString(): string }): number {
  const num = globalThis.Number(int64.toString());
  if (num > globalThis.Number.MAX_SAFE_INTEGER) {
    throw new globalThis.Error("Value is larger than Number.MAX_SAFE_INTEGER");
  }
  if (num < globalThis.Number.MIN_SAFE_INTEGER) {
    throw new globalThis.Error("Value is smaller than Number.MIN_SAFE_INTEGER");
  }
  return num;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  create(base?: DeepPartial<T>): T;
  fromPartial(object: DeepPartial<T>): T;
}
