export { WebAuthenticationClient } from './proto/AuthenticationServiceClientPb'
export * as authentication from './proto/authentication_pb'
export { WebPlayClient } from './proto/PlayServiceClientPb'
export * as play from './proto/play_pb'
export { ClientLocalizationClient } from './proto/LocalizationServiceClientPb'
export * as localization from './proto/localization_pb'
export { WebReportingClient } from './proto/ReportingServiceClientPb'
export * as reporting from './proto/reporting_pb'
